In [ ]:
import pandas as pd
import numpy as np

import re
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# load dataset using pandas
df = pd.read_csv("/content/magic_bricks_data.csv")

In [ ]:
df

,Unnamed: 0,society_name,price,location,area
0,0,NaN,₹2.24 Cr,4 BHK Apartment for Sale in Geras Island of Jo...,Carpet Area1830 sqftUnder ConstructionPoss. by...
1,1,NaN,₹3.45 Cr,4 BHK Apartment for Sale in Malpani M Soul Str...,Carpet Area2059 sqftUnder ConstructionPoss. by...
2,2,Godrej Ivara,₹3.09 Cr,"4 BHK Apartment for Sale in Godrej Ivara, Khar...",Carpet Area1550 sqftUnder ConstructionPoss. by...
3,3,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...
4,4,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...
...,...,...,...,...,...
1293,1293,Sterling Villa Grande,₹7.20 Cr,3 BHK Villa for Sale in Whitefield Bangalore,Super Area3500 sqftTransactionNew PropertyFurn...
1294,1294,Prestige Silver Oak,₹7.20 Cr,4 BHK Villa for Sale in Whitefield Bangalore,Super Area4144 sqftTransactionNew PropertyFurn...
1295,1295,Raffles Park,₹10.55 Cr,5 BHK Villa for Sale in Whitefield Bangalore,Super Area6420 sqftTransactionNew PropertyFurn...
1296,1296,Urban Poetry Of Earth,₹4.22 Cr,4 BHK Penthouse for Sale in Varthur Bangalore,Super Area3512 sqftUnder ConstructionPoss. by ...
1297,1297,Sumadhura Edition,₹3.10 Cr,4 BHK Apartment for Sale in Whitefield Bangalore,Super Area2050 sqftUnder ConstructionPoss. by ...

In [ ]:
# drop the extra index column
df = df.drop('Unnamed: 0', axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   society_name  960 non-null    object
 1   price         1298 non-null   object
 2   location      1298 non-null   object
 3   area          1298 non-null   object
dtypes: object(4)
memory usage: 40.7+ KB

In [ ]:
# checking the location column
text = ""
for i in df['location']:
  text=text + i + "\n"

In [ ]:
# regex for extracting the bhk from the location column
regex = "[\d]+\s+BHK"
df['BHK'] = df['location'].apply((lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None))

In [ ]:
df.head(5)

,society_name,price,location,area,BHK
0,NaN,₹2.24 Cr,4 BHK Apartment for Sale in Geras Island of Jo...,Carpet Area1830 sqftUnder ConstructionPoss. by...,4 BHK
1,NaN,₹3.45 Cr,4 BHK Apartment for Sale in Malpani M Soul Str...,Carpet Area2059 sqftUnder ConstructionPoss. by...,4 BHK
2,Godrej Ivara,₹3.09 Cr,"4 BHK Apartment for Sale in Godrej Ivara, Khar...",Carpet Area1550 sqftUnder ConstructionPoss. by...,4 BHK
3,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK
4,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK

In [ ]:
text=""
for i in df[df["BHK"].isna()]["location"]:
  text=text + i + "\n"

In [ ]:
Price = ""
for i in df['price']:
  Price = Price + i + "\n"

In [ ]:
# storing the location in city
City = []
for i in df['location']:
  City.append(i)

In [ ]:
# regex for only taking city in in the city column and deleting other
# and adding new column to the df
regex = "(?:Mumbai|Bangalore|Hyderabad|Ahembdabad|Ahmedabad|Pune|Chennai|Gurgaon|Kolkata|Delhi|Noida)"
df['City'] = df['location'].apply((lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None))

In [ ]:
df.head(5)

,society_name,price,location,area,BHK,City
0,NaN,₹2.24 Cr,4 BHK Apartment for Sale in Geras Island of Jo...,Carpet Area1830 sqftUnder ConstructionPoss. by...,4 BHK,Pune
1,NaN,₹3.45 Cr,4 BHK Apartment for Sale in Malpani M Soul Str...,Carpet Area2059 sqftUnder ConstructionPoss. by...,4 BHK,Pune
2,Godrej Ivara,₹3.09 Cr,"4 BHK Apartment for Sale in Godrej Ivara, Khar...",Carpet Area1550 sqftUnder ConstructionPoss. by...,4 BHK,Pune
3,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune
4,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune

In [ ]:
# regex for extracting only the sqft from the area
regex = "Area+\d+"
df['s'] = df['area'].apply((lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None))

In [ ]:
df.head(5)

,society_name,price,location,area,BHK,City,s
0,NaN,₹2.24 Cr,4 BHK Apartment for Sale in Geras Island of Jo...,Carpet Area1830 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1830
1,NaN,₹3.45 Cr,4 BHK Apartment for Sale in Malpani M Soul Str...,Carpet Area2059 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area2059
2,Godrej Ivara,₹3.09 Cr,"4 BHK Apartment for Sale in Godrej Ivara, Khar...",Carpet Area1550 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1550
3,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1684
4,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1684

In [ ]:
# regex for only taking the digits from the sqft from the 's' column
regex = "\d+"
df['sqft'] = df['s'].apply((lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None))

In [ ]:
df.head(5)

,society_name,price,location,area,BHK,City,s,sqft
0,NaN,₹2.24 Cr,4 BHK Apartment for Sale in Geras Island of Jo...,Carpet Area1830 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1830,1830
1,NaN,₹3.45 Cr,4 BHK Apartment for Sale in Malpani M Soul Str...,Carpet Area2059 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area2059,2059
2,Godrej Ivara,₹3.09 Cr,"4 BHK Apartment for Sale in Godrej Ivara, Khar...",Carpet Area1550 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1550,1550
3,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1684,1684
4,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1684,1684

In [ ]:
len(df)

1298

In [ ]:
# regex for extracting only the furnished and unfurnished text from the area column
# and making the new furnished_status column
regex = "(?:furnished|Unfurnished|Furnished|unfurnished)"
df['furnished_status'] = df['area'].apply((lambda x: re.findall(regex,x)[0] if re.findall(regex,x) else None))

In [ ]:
df.head(5)

,society_name,price,location,area,BHK,City,s,sqft,furnished_status
0,NaN,₹2.24 Cr,4 BHK Apartment for Sale in Geras Island of Jo...,Carpet Area1830 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1830,1830,Unfurnished
1,NaN,₹3.45 Cr,4 BHK Apartment for Sale in Malpani M Soul Str...,Carpet Area2059 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area2059,2059,Unfurnished
2,Godrej Ivara,₹3.09 Cr,"4 BHK Apartment for Sale in Godrej Ivara, Khar...",Carpet Area1550 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1550,1550,Unfurnished
3,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1684,1684,Unfurnished
4,Majestique Evolvus,₹2.42 Cr,4 BHK Apartment for Sale in Majestique Evolvus...,Carpet Area1684 sqftUnder ConstructionPoss. by...,4 BHK,Pune,Area1684,1684,Unfurnished

In [ ]:
# droping the extra column after extracting the usefull information
df.drop(columns = ['location','area','s'],inplace = True)

In [ ]:
df

,society_name,price,BHK,City,sqft,furnished_status
0,NaN,₹2.24 Cr,4 BHK,Pune,1830,Unfurnished
1,NaN,₹3.45 Cr,4 BHK,Pune,2059,Unfurnished
2,Godrej Ivara,₹3.09 Cr,4 BHK,Pune,1550,Unfurnished
3,Majestique Evolvus,₹2.42 Cr,4 BHK,Pune,1684,Unfurnished
4,Majestique Evolvus,₹2.42 Cr,4 BHK,Pune,1684,Unfurnished
...,...,...,...,...,...,...
1293,Sterling Villa Grande,₹7.20 Cr,3 BHK,Bangalore,3500,Unfurnished
1294,Prestige Silver Oak,₹7.20 Cr,4 BHK,Bangalore,4144,Unfurnished
1295,Raffles Park,₹10.55 Cr,5 BHK,Bangalore,6420,Unfurnished
1296,Urban Poetry Of Earth,₹4.22 Cr,4 BHK,Bangalore,3512,Unfurnished
1297,Sumadhura Edition,₹3.10 Cr,4 BHK,Bangalore,2050,Unfurnished

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   society_name      960 non-null    object
 1   price             1298 non-null   object
 2   BHK               1172 non-null   object
 3   City              1238 non-null   object
 4   sqft              1298 non-null   object
 5   furnished_status  1172 non-null   object
dtypes: object(6)
memory usage: 61.0+ KB

In [ ]:
df.to_csv('ragex_done_ready_for_eda.csv',index = False)

In [ ]:
1298 -1172

126