In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# loading csv file using pandas
df = pd.read_csv("/content/ragex_done_ready_for_eda.csv")

In [ ]:
df

,society_name,price,BHK,City,sqft,furnished_status
0,NaN,₹2.24 Cr,4 BHK,Pune,1830,Unfurnished
1,NaN,₹3.45 Cr,4 BHK,Pune,2059,Unfurnished
2,Godrej Ivara,₹3.09 Cr,4 BHK,Pune,1550,Unfurnished
3,Majestique Evolvus,₹2.42 Cr,4 BHK,Pune,1684,Unfurnished
4,Majestique Evolvus,₹2.42 Cr,4 BHK,Pune,1684,Unfurnished
...,...,...,...,...,...,...
1293,Sterling Villa Grande,₹7.20 Cr,3 BHK,Bangalore,3500,Unfurnished
1294,Prestige Silver Oak,₹7.20 Cr,4 BHK,Bangalore,4144,Unfurnished
1295,Raffles Park,₹10.55 Cr,5 BHK,Bangalore,6420,Unfurnished
1296,Urban Poetry Of Earth,₹4.22 Cr,4 BHK,Bangalore,3512,Unfurnished
1297,Sumadhura Edition,₹3.10 Cr,4 BHK,Bangalore,2050,Unfurnished

In [ ]:
df.iloc[185]

society_name        The Omaxe State
price                       ₹75 Cr
BHK                             NaN
City                          Delhi
sqft                             10
furnished_status                NaN
Name: 185, dtype: object

In [ ]:
# checking for the detailed information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   society_name      960 non-null    object
 1   price             1298 non-null   object
 2   BHK               1172 non-null   object
 3   City              1238 non-null   object
 4   sqft              1298 non-null   int64
 5   furnished_status  1172 non-null   object
dtypes: int64(1), object(5)
memory usage: 61.0+ KB

In [ ]:
# checking for null values
df.isna().sum()

society_name        338
price                 0
BHK                 126
City                 60
sqft                  0
furnished_status    126
dtype: int64

In [ ]:
# dropping the null values because not getting any insights from keeping them
df.dropna(subset=['society_name'],inplace = True)

In [ ]:
df.isna().sum()

society_name         0
price                0
BHK                 74
City                44
sqft                 0
furnished_status    75
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 960 entries, 2 to 1297
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   society_name      960 non-null    object
 1   price             960 non-null    object
 2   BHK               886 non-null    object
 3   City              916 non-null    object
 4   sqft              960 non-null    int64
 5   furnished_status  885 non-null    object
dtypes: int64(1), object(5)
memory usage: 52.5+ KB

In [ ]:
df.head(5)

                society_name      price    BHK  City  sqft furnished_status
2               Godrej Ivara  ₹3.09 Cr   4 BHK  Pune  1550      Unfurnished
3         Majestique Evolvus  ₹2.42 Cr   4 BHK  Pune  1684      Unfurnished
4         Majestique Evolvus  ₹2.42 Cr   4 BHK  Pune  1684      Unfurnished
5  Rachana Bella Casa Royale  ₹1.53 Cr   3 BHK  Pune  1166      Unfurnished
6              Nyati Emerald  ₹1.75 Cr   3 BHK  Pune  1213      Unfurnished

In [ ]:
# checking for duplicates
df.duplicated().sum()

np.int64(198)

In [ ]:
# drop the duplicates
df.drop_duplicates(inplace = True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(762, 6)

In [ ]:
df.ndim

2

###**Price Column Should Be Numeric**

In [ ]:
# first replace the special chacracter like '₹' and '.' from epmpty string
# then checked if the value is cr then so add the zeros as per the condition
# then checked if the value is lakh then add the required zero as per the conditon

df["price"] = [i.replace("₹","").replace("."," ") for i in df["price"]]
v = []
for i in df["price"]:
  j = i.split()

  if "Cr" in j:
    if len(j) == 3:
      if len(j[1]) == 1:
          v.append([j[0],j[1],'000000'])
      elif len(j[1]) == 2:
          v.append([j[0],j[1],'00000'])
    elif len(j) == 2:
      v.append([j[0],'0000000'])

  elif "Lac" in j:
    if len(j) == 3:
      if len(j[1]) == 1:
          v.append([j[0],j[1],'0000'])
      elif len(j[1]) == 2:
          v.append([j[0],j[1],'000'])
    elif len(j) == 2:
      v.append([j[0],'00000'])

  else:
    v.append(np.nan)

df["price"]=["".join(i) for i in v]
df["price"]= df['price'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 2 to 1297
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   society_name      762 non-null    object
 1   price             762 non-null    float64
 2   BHK               707 non-null    object
 3   City              719 non-null    object
 4   sqft              762 non-null    int64
 5   furnished_status  706 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 41.7+ KB

In [ ]:
df[df["City"]=="Pune"]

                  society_name       price    BHK  City  sqft furnished_status
2                 Godrej Ivara  30900000.0  4 BHK  Pune  1550      Unfurnished
3           Majestique Evolvus  24200000.0  4 BHK  Pune  1684      Unfurnished
5    Rachana Bella Casa Royale  15300000.0  3 BHK  Pune  1166      Unfurnished
6                Nyati Emerald  17500000.0  3 BHK  Pune  1213      Unfurnished
7                Lodha Massimo  78400000.0  5 BHK  Pune  3673      Unfurnished
..                         ...         ...    ...   ...   ...              ...
409                ANP Privado  75000000.0  4 BHK  Pune  3000      Unfurnished
410              Nyati Emerald  12000000.0  2 BHK  Pune   838      Unfurnished
414              Lodha Massimo  65800000.0  5 BHK  Pune  3085      Unfurnished
415    Utsav Homes The Address  22000000.0  3 BHK  Pune  1350      Unfurnished
416         Kumar Parth Towers  10800000.0  2 BHK  Pune   796      Unfurnished

[80 rows x 6 columns]

In [ ]:
df.loc[df['City'].isna()]

,society_name,price,BHK,City,sqft,furnished_status
30,Kumar Surakasha,14500000.0,3 BHK,NaN,1450,Furnished
31,Terraza,39500000.0,3 BHK,NaN,1750,Furnished
32,Ganga Liviano,15700000.0,2 BHK,NaN,870,Furnished
33,Venkatesh Graffiti,8500000.0,2 BHK,NaN,785,Furnished
34,Vilas Prime Panache C Wing,18000000.0,2 BHK,NaN,946,Furnished
35,Bharati Vihar,9800000.0,2 BHK,NaN,1097,Furnished
36,Gayatree LandMark Phase 2,11000000.0,2 BHK,NaN,798,Furnished
37,Royal cataleya,5600000.0,2 BHK,NaN,680,Unfurnished
38,J S Chandrabhaga Residency,4750000.0,1 BHK,NaN,372,Furnished
39,Pristine Pacific 1,4600000.0,1 BHK,NaN,650,Unfurnished
40,Pristine Pacific 1,4800000.0,1 BHK,NaN,648,Unfurnished
41,Gada Anutham,16000000.0,3 BHK,NaN,1050,Furnished
42,Mark Nirvana,6000000.0,2 BHK,NaN,700,Furnished
43,Vasant Utsav,7400000.0,2 BHK,NaN,892,Furnished
45,Xrbia Sneh Properties,1500000.0,2 BHK,NaN,450,Unfurnished
46,Shiv Sai Paradise,6800000.0,2 BHK,NaN,730,Furnished
49,Ganga Fernhill,3800000.0,1 BHK,NaN,625,Unfurnished
50,Nakshatra I Land,4200000.0,1 BHK,NaN,471,Unfurnished
51,Swami Samruddhi,5000000.0,1 BHK,NaN,427,Furnished
52,Gagan Emerald,8500000.0,3 BHK,NaN,1094,Unfurnished
54,Gagan Horizon Akanksha,2000000.0,1 BHK,NaN,396,Unfurnished
55,Gagan Horizon Akanksha,2500000.0,1 BHK,NaN,414,Furnished
57,Gagan 33,37500000.0,3 BHK,NaN,3102,Unfurnished
58,Estado Presidential,21000000.0,4 BHK,NaN,2414,Unfurnished
59,Skyi Songbirds,9000000.0,2 BHK,NaN,1008,Furnished
90,kanjur Vinayak Apartment,14500000.0,2 BHK,NaN,580,Furnished
92,Tista Arpit,8500000.0,1 BHK,NaN,354,Unfurnished
93,Rachna Garden,22500000.0,3 BHK,NaN,870,Furnished
95,JP North Aviva,6200000.0,1 BHK,NaN,360,Furnished
96,Madhuban Township,7000000.0,2 BHK,NaN,785,Furnished
97,Thakur Prasad Apartment,8200000.0,1 BHK,NaN,360,Unfurnished
101,Heera Panna,8700000.0,2 BHK,NaN,700,Furnished
103,Satnam Leela,24000000.0,2 BHK,NaN,650,Furnished
104,Star Sky Sayba Heights,8500000.0,1 BHK,NaN,400,Furnished
108,Bhoomi Gokul,23000000.0,2 BHK,NaN,785,Furnished
109,Prathampad Apartments,19000000.0,2 BHK,NaN,720,Unfurnished
113,Gokuldham,18000000.0,1 BHK,NaN,450,Furnished
114,St Anthony Apartment,36000000.0,2 BHK,NaN,720,Furnished
115,Classic View CHS,17500000.0,2 BHK,NaN,630,Furnished
116,Rivali Park,43000000.0,3 BHK,NaN,1296,Furnished
117,Evershine Millenium Paradise,18000000.0,2 BHK,NaN,583,Unfurnished
118,Evershine Millenium Paradise,29000000.0,2 BHK,NaN,756,Furnished
119,Evershine Green,33000000.0,3 BHK,NaN,972,Furnished

In [ ]:
# as per the known information filled index of 30 to 70 with Pune because
# from 1 to index 30 are Pune

df.loc[30:70, 'City'] = df.loc[30:70, 'City'].fillna("Pune")

In [ ]:
# as per the known information filled index of 71 to 119 with Mumbai
# because after 119 there is Mumbai

df.loc[71:119, 'City'] = df.loc[71:119, 'City'].fillna("Mumbai")

In [ ]:
df.iloc[30:119].tail(25)

,society_name,price,BHK,City,sqft,furnished_status
124,Escaso Platinum Sicily,24700000.0,2 BHK,Mumbai,841,Unfurnished
125,Kamdhenu Crown,49100000.0,3 BHK,Mumbai,1483,Unfurnished
126,Emperia Hill Crest,6270000.0,2 BHK,Mumbai,564,Unfurnished
127,Kamdhenu Pinnacle,23900000.0,3 BHK,Mumbai,881,Unfurnished
128,Surana Harmony,3900000.0,1 BHK,Mumbai,437,Unfurnished
129,Godrej Varanya Phase 2,37800000.0,3 BHK,Mumbai,1121,Unfurnished
130,Embassy Park Panvel,10500000.0,2 BHK,Mumbai,699,Unfurnished
131,Tricity Aura,7010000.0,2 BHK,Mumbai,600,Unfurnished
132,Ravriya Neelkanth Darshan,14900000.0,2 BHK,Mumbai,990,Unfurnished
133,Shri Ashtavinayak Vinayak Vista,6780000.0,2 BHK,Mumbai,1037,Unfurnished
134,Techno Shreeji Destiny,13000000.0,NaN,Mumbai,840,NaN
136,Dream Ikon,10900000.0,NaN,Mumbai,675,NaN
137,The Arena at Hiranandani Fortune city,30500000.0,4 BHK,Mumbai,1896,Unfurnished
138,Goodwill Wisteria,72100000.0,6 BHK,Mumbai,2338,Unfurnished
139,Paradise Sai World Empire,19400000.0,2 BHK,Mumbai,877,Unfurnished
140,Moreshwar 19 East,22300000.0,2 BHK,Mumbai,700,Unfurnished
142,Balaji Delta Palm Beach,37900000.0,3 BHK,Mumbai,1499,Unfurnished
143,Satyam Next Level Kharghar Central,17900000.0,3 BHK,Mumbai,856,Unfurnished
144,Superb Maximus City,7410000.0,2 BHK,Mumbai,706,Unfurnished
145,Vishwa Plan M Business Park,26000000.0,NaN,Mumbai,810,NaN
146,Raheja Solaris III,44200000.0,4 BHK,Mumbai,1650,Unfurnished
147,Arihant Adarsh Phase I,5380000.0,2 BHK,Mumbai,578,Unfurnished
148,Cyber Square 1,54000000.0,NaN,Mumbai,2879,NaN
149,Delta Luxuria,28000000.0,3 BHK,Mumbai,1169,Unfurnished
150,M3M Skycity,37500000.0,3 BHK,Gurgaon,1429,Furnished

In [ ]:
# Checking for the statistical discription of the numeric column
df.describe(include = [int,float])

              price          sqft
count  7.620000e+02    762.000000
mean   6.455996e+07   2032.517060
std    2.411410e+08   1431.792294
min    7.900000e+05     10.000000
25%    1.690000e+07   1159.250000
50%    3.050000e+07   1689.000000
75%    6.225000e+07   2470.000000
max    6.083100e+09  15000.000000

In [ ]:
# There is outlier in the data
df['price'].max()

6083100000.0

In [ ]:




df[df["price"]==6083100000.0]
# df["price"].max()

          society_name         price    BHK     City  sqft furnished_status
875  Pavani North Star  6.083100e+09  2 BHK  Chennai   700        Furnished

In [ ]:
df[df["society_name"]=="Pavani North Star"]

          society_name         price    BHK     City  sqft furnished_status
875  Pavani North Star  6.083100e+09  2 BHK  Chennai   700        Furnished

In [ ]:


df.drop(875,inplace = True)

In [ ]:
def checking_out(df,col):
  global Q1,Q3,IQR,LE,UE
  Q1  = df[col].quantile(0.25)
  Q3  = df[col].quantile(0.75)
  IQR = Q3-Q1
  LE  = Q1-(1.5*IQR)
  UE  = Q3+(1.5*IQR)

  df1=df[(df[col]<LE) | (df[col]>UE)]
  return df1

In [ ]:
checking_out(df,"price")

,society_name,price,BHK,City,sqft,furnished_status
184,Unity The Amaryllis Phase 2,1.430000e+08,5 BHK,Delhi,5236,Unfurnished
185,The Omaxe State,7.500000e+08,NaN,Delhi,10,NaN
190,The Omaxe State,1.200000e+09,NaN,Delhi,8000,NaN
204,Vasant Vihar Builder Floor,1.350000e+08,4 BHK,Delhi,400,Unfurnished
223,Godrej Connaught One,1.980000e+08,3 BHK,Delhi,2201,Furnished
228,Godrej Connaught One,2.090000e+08,3 BHK,Delhi,2201,Unfurnished
245,Godrej Avenue Eleven,3.000000e+08,4 BHK,Mumbai,2459,Unfurnished
254,Lodha Park,2.076000e+08,5 BHK,Mumbai,2532,Unfurnished
260,Equinox Embassy Citadel,1.306000e+08,3 BHK,Mumbai,1840,Unfurnished
262,Godrej Trilogy Seafront,1.661000e+08,3 BHK,Mumbai,1661,Unfurnished
265,Prestige Jasdan Classic,1.438000e+08,4 BHK,Mumbai,2302,Unfurnished
266,Raheja Modern Vivarea,2.012000e+08,5 BHK,Mumbai,2809,Unfurnished
271,The Wadhwa Artek Park,1.351000e+08,4 BHK,Mumbai,2055,Unfurnished
272,The Wadhwa Artek Park,1.450000e+08,4 BHK,Mumbai,2205,Unfurnished
274,The Wadhwa Artek Park,2.359000e+08,5 BHK,Mumbai,3630,Unfurnished
399,Jhamtani SpaceBiz,1.913000e+08,NaN,Pune,7740,NaN
457,Phoenix Kessaku,2.689000e+08,4 BHK,Bangalore,6559,Unfurnished
462,Assetz 63 Degree East,1.387300e+09,2 BHK,Bangalore,1159,Unfurnished
463,TVS Emerald Cascadia,1.523000e+08,4 BHK,Bangalore,5244,Unfurnished
473,Indraprastha Schon,2.600000e+08,4 BHK,Bangalore,7057,Furnished
477,Prestige Kenilworth,1.449000e+08,4 BHK,Bangalore,2800,Unfurnished
519,Down By The Water,1.460000e+08,4 BHK,Bangalore,6480,Unfurnished
599,DLF Camellias,7.341000e+08,4 BHK,Gurgaon,7196,Unfurnished
607,Alpha Corp Gurgaon One,1.350000e+08,4 BHK,Gurgaon,4762,Unfurnished
933,Jubilee Hills Complex,5.800000e+08,6 BHK,Hyderabad,15000,Furnished
1058,HM Central Park,1.683000e+08,5 BHK,Mumbai,1725,Unfurnished
1059,Kalpataru Prive,1.090800e+09,7 BHK,Mumbai,9008,Unfurnished
1061,Kalpataru Prive,4.293000e+08,4 BHK,Mumbai,3435,Unfurnished
1062,Lodha Seamont,4.050000e+08,4 BHK,Mumbai,3000,Unfurnished
1064,Runwal Malabar,3.120000e+08,4 BHK,Mumbai,2600,Unfurnished
1065,Lodha Seamont,1.500000e+08,3 BHK,Mumbai,1560,Furnished
1067,Dhuleva Seven,2.204000e+08,4 BHK,Mumbai,2449,Unfurnished
1069,Anita Building,1.550000e+08,3 BHK,Mumbai,1550,Furnished
1073,Lodha Seamont,1.499000e+08,3 BHK,Mumbai,1350,Furnished
1075,Arkade Rise,2.000000e+08,4 BHK,Mumbai,1590,Furnished
1085,Satellite Sesen,5.000000e+08,10 BHK,Mumbai,10,Unfurnished
1090,Kalpataru Amare,2.405000e+08,5 BHK,Mumbai,3700,Unfurnished
1091,Rustomjee Ashiana,1.550000e+08,4 BHK,Mumbai,1954,Unfurnished
1099,Govind Vihar Apartment,1.800000e+08,4 BHK,Mumbai,2599,Furnished
1110,K Raheja Maestro,2.399000e+08,4 BHK,Mumbai,2864,Furnished
1117,Kalpataru Amare,1.370000e+08,4 BHK,Mumbai,1845,Furnished
1139,Radius 10 BKC,1.559000e+08,4 BHK,Mumbai,2237,Unfurnished
1144,Adani Ten BKC,1.677000e+08,4 BHK,Mumbai,2237,Unfurnished
1153,Jolly Maker Apartment,1.350000e+08,3 BHK,Mumbai,1615,Furnished
1154,Maker Tower,3.100000e+08,4 BHK,Mumbai,3100,Furnished
1161,Jolly Maker Apartment,1.850000e+08,3 BHK,Mumbai,1188,Furnished
1166,Jolly Maker Apartment,1.850000e+08,3 BHK,Mumbai,1650,Furnished
1170,Maker Tower,3.000000e+08,4 BHK,Mumbai,3000,Furnished
1175,Maker Tower,2.000000e+08,4 BHK,Mumbai,2100,Furnished
1184,India Bulls Sky Forest,1.704000e+08,3 BHK,Mumbai,3589,Unfurnished
1186,Equinox Embassy Citadel,1.349000e+08,3 BHK,Mumbai,1900,Unfurnished
1187,Equinox Embassy Citadel,3.947000e+08,5 BHK,Mumbai,5560,Unfurnished
1195,Equinox Embassy Citadel,2.100000e+08,4 BHK,Mumbai,3000,Unfurnished
1197,Peninsula Corporate Park,5.500000e+08,NaN,Mumbai,9500,NaN
1199,Lodha The World Towers,1.650000e+08,3 BHK,Mumbai,2200,Furnished
1203,Equinox Embassy Citadel,1.380000e+08,3 BHK,Mumbai,1840,Unfurnished
1205,One Avighna Park,3.500000e+08,5 BHK,Mumbai,4800,Unfurnished

In [ ]:
UE

np.float64(128400000.0)

In [ ]:
LE

np.float64(-50000000.0)

In [ ]:
IQR

np.float64(44600000.0)

In [ ]:

df['furnished_status'].value_counts()

furnished_status
Unfurnished    533
Furnished      172
Name: count, dtype: int64

In [ ]:
df.shape

(761, 6)

In [ ]:
df.reset_index(inplace = True)

In [ ]:
df

,index,society_name,price,BHK,City,sqft,furnished_status
0,2,Godrej Ivara,30900000.0,4 BHK,Pune,1550,Unfurnished
1,3,Majestique Evolvus,24200000.0,4 BHK,Pune,1684,Unfurnished
2,5,Rachana Bella Casa Royale,15300000.0,3 BHK,Pune,1166,Unfurnished
3,6,Nyati Emerald,17500000.0,3 BHK,Pune,1213,Unfurnished
4,7,Lodha Massimo,78400000.0,5 BHK,Pune,3673,Unfurnished
...,...,...,...,...,...,...,...
756,1293,Sterling Villa Grande,72000000.0,3 BHK,Bangalore,3500,Unfurnished
757,1294,Prestige Silver Oak,72000000.0,4 BHK,Bangalore,4144,Unfurnished
758,1295,Raffles Park,105500000.0,5 BHK,Bangalore,6420,Unfurnished
759,1296,Urban Poetry Of Earth,42200000.0,4 BHK,Bangalore,3512,Unfurnished
760,1297,Sumadhura Edition,31000000.0,4 BHK,Bangalore,2050,Unfurnished

In [ ]:
df.drop(columns = ['index'],inplace = True)

In [ ]:





# df['furnished_status'].fillna(method="ffill",inplace = True)
df['furnished_status'] = df['furnished_status'].ffill()

In [ ]:
df['furnished_status'].isna().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   society_name      761 non-null    object
 1   price             761 non-null    float64
 2   BHK               706 non-null    object
 3   City              761 non-null    object
 4   sqft              761 non-null    int64
 5   furnished_status  761 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 35.8+ KB

In [ ]:
# df['BHK'] = [str(i).replace("BHK","").strip() if i !="nan" else np.nan for i in df['BHK']]

df["bhk"]=[np.nan if i =="nan" else i for i in  df["BHK"]]
df["bhk"]=[str(i).replace("BHK","").strip() for i in df["bhk"]]
df["bhk"]=df["bhk"].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   society_name      761 non-null    object
 1   price             761 non-null    float64
 2   BHK               706 non-null    object
 3   City              761 non-null    object
 4   sqft              761 non-null    int64
 5   furnished_status  761 non-null    object
 6   bhk               706 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 41.7+ KB

In [ ]:
df['bhk'] = df.groupby('City')['bhk'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df["bhk"].isna().sum()

np.int64(0)

In [ ]:
df

,society_name,price,BHK,City,sqft,furnished_status,bhk
0,Godrej Ivara,30900000.0,4 BHK,Pune,1550,Unfurnished,4.0
1,Majestique Evolvus,24200000.0,4 BHK,Pune,1684,Unfurnished,4.0
2,Rachana Bella Casa Royale,15300000.0,3 BHK,Pune,1166,Unfurnished,3.0
3,Nyati Emerald,17500000.0,3 BHK,Pune,1213,Unfurnished,3.0
4,Lodha Massimo,78400000.0,5 BHK,Pune,3673,Unfurnished,5.0
...,...,...,...,...,...,...,...
756,Sterling Villa Grande,72000000.0,3 BHK,Bangalore,3500,Unfurnished,3.0
757,Prestige Silver Oak,72000000.0,4 BHK,Bangalore,4144,Unfurnished,4.0
758,Raffles Park,105500000.0,5 BHK,Bangalore,6420,Unfurnished,5.0
759,Urban Poetry Of Earth,42200000.0,4 BHK,Bangalore,3512,Unfurnished,4.0
760,Sumadhura Edition,31000000.0,4 BHK,Bangalore,2050,Unfurnished,4.0

In [ ]:
df.drop(columns = ['BHK'],inplace = True)

In [ ]:
df

,society_name,price,City,sqft,furnished_status,bhk
0,Godrej Ivara,30900000.0,Pune,1550,Unfurnished,4.0
1,Majestique Evolvus,24200000.0,Pune,1684,Unfurnished,4.0
2,Rachana Bella Casa Royale,15300000.0,Pune,1166,Unfurnished,3.0
3,Nyati Emerald,17500000.0,Pune,1213,Unfurnished,3.0
4,Lodha Massimo,78400000.0,Pune,3673,Unfurnished,5.0
...,...,...,...,...,...,...
756,Sterling Villa Grande,72000000.0,Bangalore,3500,Unfurnished,3.0
757,Prestige Silver Oak,72000000.0,Bangalore,4144,Unfurnished,4.0
758,Raffles Park,105500000.0,Bangalore,6420,Unfurnished,5.0
759,Urban Poetry Of Earth,42200000.0,Bangalore,3512,Unfurnished,4.0
760,Sumadhura Edition,31000000.0,Bangalore,2050,Unfurnished,4.0

In [ ]:
def checking_out(df,col):
  global Q1,Q3,IQR,LE,UE
  Q1  = df[col].quantile(0.25)
  Q3  = df[col].quantile(0.75)
  IQR = Q3-Q1
  LE  = Q1-(1.5*IQR)
  UE  = Q3+(1.5*IQR)

  df1=df[(df[col]<LE) | (df[col]>UE)]
  return df1

In [ ]:
checking_out(df,"sqft")

,society_name,price,City,sqft,furnished_status,bhk
52,SHELADIA TREETOP,5.000000e+07,Ahmedabad,6262,Unfurnished,4.0
67,Adani Belrosa,6.100000e+07,Ahmedabad,6911,Unfurnished,6.0
71,Aristo The Opus And Aatmantan,2.890000e+07,Ahmedabad,4455,Unfurnished,4.0
133,Indiabulls Enigma,8.000000e+07,Gurgaon,7430,Unfurnished,5.0
138,Unity The Amaryllis Phase 2,1.430000e+08,Delhi,5236,Unfurnished,5.0
141,The Omaxe State,1.200000e+09,Delhi,8000,Unfurnished,3.0
230,Marvel Sonnet,5.250000e+07,Pune,4800,Furnished,4.0
232,Sky Belvedere,8.500000e+07,Pune,4505,Furnished,4.0
254,Jhamtani SpaceBiz,1.913000e+08,Pune,7740,Unfurnished,3.0
284,Mana Jardin Neo,1.056000e+08,Bangalore,7161,Unfurnished,5.0
299,Phoenix Kessaku,2.689000e+08,Bangalore,6559,Unfurnished,4.0
305,TVS Emerald Cascadia,1.523000e+08,Bangalore,5244,Unfurnished,4.0
310,Indraprastha Schon,2.600000e+08,Bangalore,7057,Furnished,4.0
328,Down By The Water,1.460000e+08,Bangalore,6480,Unfurnished,4.0
329,Down By The Water,1.124000e+08,Bangalore,4980,Unfurnished,4.0
366,SRS Luxury Floors,6.250000e+07,Gurgaon,5200,Unfurnished,5.0
375,DLF Camellias,7.341000e+08,Gurgaon,7196,Unfurnished,4.0
383,Alpha Corp Gurgaon One,1.350000e+08,Gurgaon,4762,Unfurnished,4.0
423,SRIPSK Palladina,6.950000e+07,Kolkata,4965,Unfurnished,4.0
460,Swati Trinity,8.220000e+07,Ahmedabad,8951,Unfurnished,4.0
467,Vraj Garden,7.150000e+07,Ahmedabad,8586,Unfurnished,4.0
479,Brigade Altius,6.910000e+07,Chennai,5054,Unfurnished,4.0
530,Skymarq By DSR,6.270000e+07,Hyderabad,5454,Unfurnished,4.0
536,Aparna Dharti,3.270000e+07,Hyderabad,7182,Unfurnished,3.0
539,Bhuvana Harmony Woods,1.250000e+07,Hyderabad,4500,Unfurnished,3.0
540,DSR The World At Jubilee Hills,1.275000e+08,Hyderabad,8499,Unfurnished,5.0
541,Phoneix Halcyon,8.750000e+07,Hyderabad,6358,Unfurnished,4.0
543,Phoenix Everest,8.500000e+07,Hyderabad,5358,Furnished,4.0
546,Jubilee Hills Complex,5.800000e+08,Hyderabad,15000,Furnished,6.0
558,Sri Aditya Lifestyle,1.000000e+08,Hyderabad,5330,Furnished,4.0
587,Auro The Pearl,7.560000e+07,Hyderabad,5400,Unfurnished,4.0
590,Lodha Bellezza,5.550000e+07,Hyderabad,4761,Unfurnished,4.0
611,Kalpataru Prive,1.090800e+09,Mumbai,9008,Unfurnished,7.0
676,Equinox Embassy Citadel,3.947000e+08,Mumbai,5560,Unfurnished,5.0
680,Peninsula Corporate Park,5.500000e+08,Mumbai,9500,Unfurnished,3.0
687,One Avighna Park,3.500000e+08,Mumbai,4800,Unfurnished,5.0
703,DNR Highline,1.000000e+08,Bangalore,5153,Unfurnished,5.0
717,KMB La Palazzo,8.650000e+07,Bangalore,4893,Furnished,4.0
746,Prestige Ozone,6.420000e+07,Bangalore,4800,Unfurnished,4.0
750,DSR Elixir,4.750000e+07,Bangalore,4615,Unfurnished,4.0
758,Raffles Park,1.055000e+08,Bangalore,6420,Unfurnished,5.0

In [ ]:
# from scipy.stats import zscore
# mean = df['price'].mean()
# std = df['price'].std()

# z = (df['sqft'] - mean) / std

In [ ]:
df

,society_name,price,City,sqft,furnished_status,bhk
0,Godrej Ivara,30900000.0,Pune,1550,Unfurnished,4.0
1,Majestique Evolvus,24200000.0,Pune,1684,Unfurnished,4.0
2,Rachana Bella Casa Royale,15300000.0,Pune,1166,Unfurnished,3.0
3,Nyati Emerald,17500000.0,Pune,1213,Unfurnished,3.0
4,Lodha Massimo,78400000.0,Pune,3673,Unfurnished,5.0
...,...,...,...,...,...,...
756,Sterling Villa Grande,72000000.0,Bangalore,3500,Unfurnished,3.0
757,Prestige Silver Oak,72000000.0,Bangalore,4144,Unfurnished,4.0
758,Raffles Park,105500000.0,Bangalore,6420,Unfurnished,5.0
759,Urban Poetry Of Earth,42200000.0,Bangalore,3512,Unfurnished,4.0
760,Sumadhura Edition,31000000.0,Bangalore,2050,Unfurnished,4.0

In [ ]:
df.describe(include = 'all')

,society_name,price,City,sqft,furnished_status,bhk
count,761,7.610000e+02,761,761.000000,761,761.000000
unique,550,NaN,10,NaN,2,NaN
top,Sobha Rajvilas,NaN,Mumbai,NaN,Unfurnished,NaN
freq,14,NaN,173,NaN,579,NaN
mean,NaN,5.665124e+07,NaN,2034.268068,NaN,3.269382
std,NaN,1.024756e+08,NaN,1431.917313,NaN,0.901590
min,NaN,7.900000e+05,NaN,10.000000,NaN,1.000000
25%,NaN,1.690000e+07,NaN,1160.000000,NaN,3.000000
50%,NaN,3.050000e+07,NaN,1690.000000,NaN,3.000000
75%,NaN,6.150000e+07,NaN,2470.000000,NaN,4.000000
max,NaN,1.387300e+09,NaN,15000.000000,NaN,10.000000

In [ ]:
df.describe(include = ['int','float'])

              price          sqft         bhk
count  7.610000e+02    761.000000  761.000000
mean   5.665124e+07   2034.268068    3.269382
std    1.024756e+08   1431.917313    0.901590
min    7.900000e+05     10.000000    1.000000
25%    1.690000e+07   1160.000000    3.000000
50%    3.050000e+07   1690.000000    3.000000
75%    6.150000e+07   2470.000000    4.000000
max    1.387300e+09  15000.000000   10.000000

In [ ]:
# we are storing all the flats whoes price are inside 100 cr because in 2 and 3 bhk there are outliers

df[(df['price']>1000000000) & (((df['bhk']==2) |(df['bhk']==3) )) ]

,society_name,price,City,sqft,furnished_status,bhk
141,The Omaxe State,1.200000e+09,Delhi,8000,Unfurnished,3.0
304,Assetz 63 Degree East,1.387300e+09,Bangalore,1159,Unfurnished,2.0

In [ ]:
df.drop(index=[141,304],inplace=True)

In [ ]:
df.shape

(759, 6)

In [ ]:
df[(df['price']>1000000000) & (((df['bhk']==2) |(df['bhk']==3) )) ]

Empty DataFrame
Columns: [society_name, price, City, sqft, furnished_status, bhk]
Index: []

In [ ]:
df[(df['price']>800000000) & (df['furnished_status']=='Unfurnished') ]

        society_name         price    City  sqft furnished_status  bhk
611  Kalpataru Prive  1.090800e+09  Mumbai  9008      Unfurnished  7.0

In [ ]:
df.drop(index=[611],inplace=True)

In [ ]:
df[(df['price']>800000000) & (df['furnished_status']=='Unfurnished') ]

Empty DataFrame
Columns: [society_name, price, City, sqft, furnished_status, bhk]
Index: []

In [ ]:
df[(df['price']>500000000) & (((df['bhk']==3) |(df['bhk']==4) )) ]

,society_name,price,City,sqft,furnished_status,bhk
139,The Omaxe State,750000000.0,Delhi,10,Unfurnished,3.0
375,DLF Camellias,734100000.0,Gurgaon,7196,Unfurnished,4.0
680,Peninsula Corporate Park,550000000.0,Mumbai,9500,Unfurnished,3.0

In [ ]:
df.drop(index=[139,375,680],inplace=True)

In [ ]:
df[(df['price']>500000000) & (df['bhk']==6)]

,society_name,price,City,sqft,furnished_status,bhk
546,Jubilee Hills Complex,580000000.0,Hyderabad,15000,Furnished,6.0

In [ ]:
df.drop(index=[546],inplace=True)

In [ ]:
df.to_csv("6 oultiler removed last visulaization.csv",index = False)

In [ ]:
df2 = pd.read_csv("/content/6 oultiler removed last visulaization.csv")

In [ ]:
checking_out(df2,"price")

,society_name,price,City,sqft,furnished_status,bhk
138,Unity The Amaryllis Phase 2,143000000.0,Delhi,5236,Unfurnished,5.0
145,Vasant Vihar Builder Floor,135000000.0,Delhi,400,Unfurnished,4.0
150,Godrej Connaught One,198000000.0,Delhi,2201,Furnished,3.0
152,Godrej Connaught One,209000000.0,Delhi,2201,Unfurnished,3.0
156,Godrej Avenue Eleven,300000000.0,Mumbai,2459,Unfurnished,4.0
165,Lodha Park,207600000.0,Mumbai,2532,Unfurnished,5.0
171,Equinox Embassy Citadel,130600000.0,Mumbai,1840,Unfurnished,3.0
173,Godrej Trilogy Seafront,166100000.0,Mumbai,1661,Unfurnished,3.0
175,Prestige Jasdan Classic,143800000.0,Mumbai,2302,Unfurnished,4.0
176,Raheja Modern Vivarea,201200000.0,Mumbai,2809,Unfurnished,5.0
180,The Wadhwa Artek Park,135100000.0,Mumbai,2055,Unfurnished,4.0
181,The Wadhwa Artek Park,145000000.0,Mumbai,2205,Unfurnished,4.0
183,The Wadhwa Artek Park,235900000.0,Mumbai,3630,Unfurnished,5.0
252,Jhamtani SpaceBiz,191300000.0,Pune,7740,Unfurnished,3.0
297,Phoenix Kessaku,268900000.0,Bangalore,6559,Unfurnished,4.0
302,TVS Emerald Cascadia,152300000.0,Bangalore,5244,Unfurnished,4.0
307,Indraprastha Schon,260000000.0,Bangalore,7057,Furnished,4.0
310,Prestige Kenilworth,144900000.0,Bangalore,2800,Unfurnished,4.0
325,Down By The Water,146000000.0,Bangalore,6480,Unfurnished,4.0
379,Alpha Corp Gurgaon One,135000000.0,Gurgaon,4762,Unfurnished,4.0
536,DSR The World At Jubilee Hills,127500000.0,Hyderabad,8499,Unfurnished,5.0
605,HM Central Park,168300000.0,Mumbai,1725,Unfurnished,5.0
606,Kalpataru Prive,429300000.0,Mumbai,3435,Unfurnished,4.0
607,Lodha Seamont,405000000.0,Mumbai,3000,Unfurnished,4.0
608,Runwal Malabar,312000000.0,Mumbai,2600,Unfurnished,4.0
609,Lodha Seamont,150000000.0,Mumbai,1560,Furnished,3.0
610,Dhuleva Seven,220400000.0,Mumbai,2449,Unfurnished,4.0
611,Anita Building,155000000.0,Mumbai,1550,Furnished,3.0
612,Lodha Seamont,149900000.0,Mumbai,1350,Furnished,3.0
613,Arkade Rise,200000000.0,Mumbai,1590,Furnished,4.0
618,Satellite Sesen,500000000.0,Mumbai,10,Unfurnished,10.0
620,Kalpataru Amare,240500000.0,Mumbai,3700,Unfurnished,5.0
621,Rustomjee Ashiana,155000000.0,Mumbai,1954,Unfurnished,4.0
625,Govind Vihar Apartment,180000000.0,Mumbai,2599,Furnished,4.0
630,K Raheja Maestro,239900000.0,Mumbai,2864,Furnished,4.0
635,Kalpataru Amare,137000000.0,Mumbai,1845,Furnished,4.0
640,Radius 10 BKC,155900000.0,Mumbai,2237,Unfurnished,4.0
645,Adani Ten BKC,167700000.0,Mumbai,2237,Unfurnished,4.0
650,Jolly Maker Apartment,135000000.0,Mumbai,1615,Furnished,3.0
651,Maker Tower,310000000.0,Mumbai,3100,Furnished,4.0
655,Jolly Maker Apartment,185000000.0,Mumbai,1188,Furnished,3.0
659,Jolly Maker Apartment,185000000.0,Mumbai,1650,Furnished,3.0
661,Maker Tower,300000000.0,Mumbai,3000,Furnished,4.0
664,Maker Tower,200000000.0,Mumbai,2100,Furnished,4.0
668,India Bulls Sky Forest,170400000.0,Mumbai,3589,Unfurnished,3.0
669,Equinox Embassy Citadel,134900000.0,Mumbai,1900,Unfurnished,3.0
670,Equinox Embassy Citadel,394700000.0,Mumbai,5560,Unfurnished,5.0
672,Equinox Embassy Citadel,210000000.0,Mumbai,3000,Unfurnished,4.0
674,Lodha The World Towers,165000000.0,Mumbai,2200,Furnished,3.0
678,Equinox Embassy Citadel,138000000.0,Mumbai,1840,Unfurnished,3.0
679,Indiabulls Sky,127500000.0,Mumbai,1290,Furnished,2.0
680,One Avighna Park,350000000.0,Mumbai,4800,Unfurnished,5.0

In [ ]:
UE

np.float64(126125000.0)

In [ ]:
LE

np.float64(-49075000.0)

In [ ]:
IQR

np.float64(43800000.0)

In [ ]:
Q1

np.float64(16625000.0)

In [ ]:
Q3

np.float64(60425000.0)

In [ ]:
checking_out(df2,"sqft")

,society_name,price,City,sqft,furnished_status,bhk
52,SHELADIA TREETOP,50000000.0,Ahmedabad,6262,Unfurnished,4.0
67,Adani Belrosa,61000000.0,Ahmedabad,6911,Unfurnished,6.0
71,Aristo The Opus And Aatmantan,28900000.0,Ahmedabad,4455,Unfurnished,4.0
133,Indiabulls Enigma,80000000.0,Gurgaon,7430,Unfurnished,5.0
138,Unity The Amaryllis Phase 2,143000000.0,Delhi,5236,Unfurnished,5.0
228,Marvel Sonnet,52500000.0,Pune,4800,Furnished,4.0
230,Sky Belvedere,85000000.0,Pune,4505,Furnished,4.0
252,Jhamtani SpaceBiz,191300000.0,Pune,7740,Unfurnished,3.0
282,Mana Jardin Neo,105600000.0,Bangalore,7161,Unfurnished,5.0
297,Phoenix Kessaku,268900000.0,Bangalore,6559,Unfurnished,4.0
302,TVS Emerald Cascadia,152300000.0,Bangalore,5244,Unfurnished,4.0
307,Indraprastha Schon,260000000.0,Bangalore,7057,Furnished,4.0
325,Down By The Water,146000000.0,Bangalore,6480,Unfurnished,4.0
326,Down By The Water,112400000.0,Bangalore,4980,Unfurnished,4.0
363,SRS Luxury Floors,62500000.0,Gurgaon,5200,Unfurnished,5.0
379,Alpha Corp Gurgaon One,135000000.0,Gurgaon,4762,Unfurnished,4.0
385,SS Linden Floors,38500000.0,Gurgaon,4392,Unfurnished,4.0
419,SRIPSK Palladina,69500000.0,Kolkata,4965,Unfurnished,4.0
448,PS Vaanya,56000000.0,Kolkata,4400,Unfurnished,5.0
456,Swati Trinity,82200000.0,Ahmedabad,8951,Unfurnished,4.0
463,Vraj Garden,71500000.0,Ahmedabad,8586,Unfurnished,4.0
475,Brigade Altius,69100000.0,Chennai,5054,Unfurnished,4.0
519,Vajra West City,32100000.0,Hyderabad,4400,Unfurnished,4.0
526,Skymarq By DSR,62700000.0,Hyderabad,5454,Unfurnished,4.0
532,Aparna Dharti,32700000.0,Hyderabad,7182,Unfurnished,3.0
535,Bhuvana Harmony Woods,12500000.0,Hyderabad,4500,Unfurnished,3.0
536,DSR The World At Jubilee Hills,127500000.0,Hyderabad,8499,Unfurnished,5.0
537,Phoneix Halcyon,87500000.0,Hyderabad,6358,Unfurnished,4.0
539,Phoenix Everest,85000000.0,Hyderabad,5358,Furnished,4.0
553,Sri Aditya Lifestyle,100000000.0,Hyderabad,5330,Furnished,4.0
582,Auro The Pearl,75600000.0,Hyderabad,5400,Unfurnished,4.0
585,Lodha Bellezza,55500000.0,Hyderabad,4761,Unfurnished,4.0
670,Equinox Embassy Citadel,394700000.0,Mumbai,5560,Unfurnished,5.0
680,One Avighna Park,350000000.0,Mumbai,4800,Unfurnished,5.0
696,DNR Highline,100000000.0,Bangalore,5153,Unfurnished,5.0
710,KMB La Palazzo,86500000.0,Bangalore,4893,Furnished,4.0
739,Prestige Ozone,64200000.0,Bangalore,4800,Unfurnished,4.0
743,DSR Elixir,47500000.0,Bangalore,4615,Unfurnished,4.0
751,Raffles Park,105500000.0,Bangalore,6420,Unfurnished,5.0

In [ ]:
UE

np.float64(4376.25)

In [ ]:
LE

np.float64(-769.75)

In [ ]:
IQR

np.float64(1286.5)